### PR TITLE
sync from floweisshardt/master

### PR DESCRIPTION
**Pull request by floweisshardt**
includes:
- data series https://github.com/floweisshardt/atf/pull/110
- lfs fix https://github.com/floweisshardt/atf/pull/111 (already pushed as cherry-picked hot fix)
- fix groundtruth handling https://github.com/floweisshardt/atf/pull/112
- ci update https://github.com/floweisshardt/atf/pull/113
- docu update https://github.com/floweisshardt/atf/pull/114
- make repetitions optional https://github.com/floweisshardt/atf/pull/118
- print result summary https://github.com/floweisshardt/atf/pull/124
- Fix analyser output and data series https://github.com/floweisshardt/atf/pull/126

### CODE REVIEW

**Review by fmessmer — DISMISSED** [review]
this should get merged and then `mojin-robotics/atf` should get "feature-freezed" until https://github.com/mojin-robotics/mojin_atf/pull/1 gets merged....

of course, re-run https://github.com/mojin-robotics/mojin_atf/pull/1 at least once with this PR merged!

**Comment by floweisshardt** [comment]
no hurry to merge this. This PR only introduces minor changes to ATF and can wait for more major features or bugfixes. https://github.com/mojin-robotics/mojin_atf/pull/1 does not depend on this PR.

Let's get https://github.com/mojin-robotics/mojin_atf/pull/1 merged without this one.

**Comment by fmessmer** [comment]
so what's the criteria then to merge this?
@floweisshardt

**Comment by floweisshardt** [comment]
> so what's the criteria then to merge this?

can be merged anytime but I'd merge this only when there's a "significant" improuvement or new features neccessary for mojin or as soon as the ATF API changes.

**Pull request merged**
